app:
  name: ui
  image:
    repository: 'onecx/onecx-announcement-ui'
  routing:
    enabled: true
    path: /mfe/announcement/
  
  operator:
    # Microfrontend
    microfrontend:
      enabled: true
      specs:
        main:
          exposedModule: "./OneCXAnnouncementModule"
          description: "OneCX Announcement UI"
          note: "OneCX Announcement UI auto import via MF operator"
          type: MODULE
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
          ANNOUCEMENT:
            CREATE: Create announcement
            DELETE: Delete announcement
            EDIT: Edit announcement
            SAVE: Update and save announcement
            SEARCH: Search announcement
            VIEW: View mode for announcement
            EXPORT: Export announcement
            IMPORT: Import announcement
    # Keycloak
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: "onecx-announcement-ui"
            
# PIPE Config
